# Generated by Django 3.1.3 on 2023-05-18 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('avatar', models.ImageField(default='avatar.png', upload_to='avatars/')),
                ('address', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Faridpur', 'Faridpur'), ('Gazipur', 'Gazipur'), ('Gopalganj', 'Gopalganj'), ('Jamalpur', 'Jamalpur'), ('Kishoreganj', 'Kishoreganj'), ('Madaripur', 'Madaripur'), ('Manikganj', 'Manikganj'), ('Munshiganj', 'Munshiganj'), ('Mymensingh', 'Mymensingh'), ('Narayanganj', 'Narayanganj'), ('Narsingdi', 'Narsingdi'), ('Netrokona', 'Netrokona'), ('Rajbari', 'Rajbari'), ('Shariatpur', 'Shariatpur'), ('Sherpur', 'Sherpur'), ('Tangail', 'Tangail'), ('Bogura', 'Bogura'), ('Joypurhat', 'Joypurhat'), ('Naogaon', 'Naogaon'), ('Natore', 'Natore'), ('Nawabganj', 'Nawabganj'), ('Pabna', 'Pabna'), ('Rajshahi', 'Rajshahi'), ('Sirajgonj', 'Sirajgonj'), ('Dinajpur', 'Dinajpur'), ('Gaibandha', 'Gaibandha'), ('Kurigram', 'Kurigram'), ('Lalmonirhat', 'Lalmonirhat'), ('Nilphamari', 'Nilphamari'), ('Panchagarh', 'Panchagarh'), ('Rangpur', 'Rangpur'), ('Thakurgaon', 'Thakurgaon'), ('Barguna', 'Barguna'), ('Barishal', 'Barishal'), ('Bhola', 'Bhola'), ('Jhalokati', 'Jhalokati'), ('Patuakhali', 'Patuakhali'), ('Pirojpur', 'Pirojpur'), ('Bandarban', 'Bandarban'), ('Brahmanbaria', 'Brahmanbaria'), ('Chandpur', 'Chandpur'), ('Chattogram', 'Chattogram'), ('Cumilla', 'Cumilla'), ("Cox's Bazar", "Cox's Bazar"), ('Feni', 'Feni'), ('Khagrachari', 'Khagrachari'), ('Lakshmipur', 'Lakshmipur'), ('Noakhali', 'Noakhali'), ('Rangamati', 'Rangamati'), ('Habiganj', 'Habiganj'), ('Maulvibazar', 'Maulvibazar'), ('Sunamganj', 'Sunamganj'), ('Sylhet', 'Sylhet'), ('Bagerhat', 'Bagerhat'), ('Chuadanga', 'Chuadanga'), ('Jashore', 'Jashore'), ('Jhenaidah', 'Jhenaidah'), ('Khulna', 'Khulna'), ('Kushtia', 'Kushtia'), ('Magura', 'Magura'), ('Meherpur', 'Meherpur'), ('Narail', 'Narail'), ('Satkhira', 'Satkhira')], default='Dhaka', max_length=15)),
                ('phoneNum', models.BigIntegerField(default=880)),
                ('power', models.FloatField(choices=[(-8, '-8'), (-7.75, '-7.75'), (-7.5, '-7.5'), (-7.25, '-7.25'), (-7.0, '-7.0'), (-6.75, '-6.75'), (-6.5, '-6.5'), (-6.25, '-6.25'), (-6.0, '-6.0'), (-5.75, '-5.75'), (-5.5, '-5.5'), (-5.25, '-5.25'), (-5.0, '-5.0'), (-4.75, '-4.75'), (-4.5, '-4.5'), (-4.25, '-4.25'), (-4.0, '-4.0'), (-3.75, '-3.75'), (-3.5, '-3.5'), (-3.25, '-3.25'), (-3.0, '-3.0'), (-2.75, '-2.75'), (-2.5, '-2.5'), (-2.25, '-2.25'), (-2.0, '-2.0'), (-1.75, '-1.75'), (-1.5, '-1.5'), (-1.25, '-1.25'), (-1.0, '-1.0'), (-0.75, '-0.75'), (-0.5, '-0.5'), (-0.25, '-0.25'), (0.0, '0.0'), (0.25, '0.25'), (0.5, '0.5'), (0.75, '0.75'), (1.0, '1.0'), (1.25, '1.25'), (1.5, '1.5'), (1.75, '1.75'), (2.0, '2.0'), (2.25, '2.25'), (2.5, '2.5'), (2.75, '2.75'), (3.0, '3.0'), (3.25, '3.25'), (3.5, '3.5'), (3.75, '3.75'), (4.0, '4.0'), (4.25, '4.25'), (4.5, '4.5'), (4.75, '4.75'), (5.0, '5.0'), (5.25, '5.25'), (5.5, '5.5'), (5.75, '5.75'), (6.0, '6.0'), (6.25, '6.25'), (6.5, '6.5'), (6.75, '6.75'), (7.0, '7.0'), (7.25, '7.25'), (7.5, '7.5'), (7.75, '7.75'), (8, '8.0')], default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
