# Generated by Django 3.1.3 on 2024-05-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20230706_1339'),
        ('movie', '0004_auto_20240530_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, editable=False, related_name='likesm', to='profiles.Profile'),
        ),
    ]
